logging:
  level:
    org.springframework.security: INFO

spring:
  resources:
    chain:
      enabled: true
      
server:
    port: 8888
    contextPath: /
    
security:
  sessions: ALWAYS
  basic:
    enabled: false